### PR TITLE
Consolidate installPlan functions

### LINKED ISSUE #100: Consolidate ApproveInstallPlan and installPlanApprove
These two methods are complementary and named in a confusing way. Maybe even overlapping part of the job. We can reduce lines of code and simplify for readability.

### PR DESCRIPTION
**Pull request by mgoerens**
closes #100

One question around installPlanApproval: When we are creating the subscription, we don't specify an installPlanApproval. My understanding is that the default value for this field is `Automatic`. I'm unsure if an operator provider can force a different default value here ? Otherwise, the installPlanApproval is always going to be `Automatic` and we actually never need to manually approve it.

Alternatively, we could also set installPlanApproval to Automatic when creating the subscription. Again, this would make the whole installPlan approval code unnecessary.

Am I missing something ? Do we want to keep the possibility to test operators being install with a `Manual` installPlanApproval in the future ?

### CODE REVIEW

**Comment by acmenezes** [comment]
> closes #100
> 
> One question around installPlanApproval: When we are creating the subscription, we don't specify an installPlanApproval. My understanding is that the default value for this field is `Automatic`. I'm unsure if an operator provider can force a different default value here ? Otherwise, the installPlanApproval is always going to be `Automatic` and we actually never need to manually approve it.
> 
> Alternatively, we could also set installPlanApproval to Automatic when creating the subscription. Again, this would make the whole installPlan approval code unnecessary.
> 
> Am I missing something ? Do we want to keep the possibility to test operators being install with a `Manual` installPlanApproval in the future ?

Hi Matthias,

Actually that's a great question and may change the direction we are going here. I guess at some point somebody brought in the manual vs automatic approval and that logic was implemented somewhere else on other projects doing something similar. That's how this part of the code came in. But you are 100% right. We can keep it all automatic as they are probably being created. But on the other hand that logic may come back when we have upgrade testing. In the end of the day we would be testing not the operator or operand but OLM itself against multiple operators if we were to change it to manual.

Anyway manual testing should still be something for the future. I think we should revamp this. Let me add other comments on the review itself.

**Review by acmenezes — CHANGES_REQUESTED** [review]
Based on the initial question it think we can eliminate completely the approval code and only wait for the installPlan to be in place. And I believe we can improve the subscription creation by adding the InstallPlanApproval field as `automatic` explicitly as well.

**Comment by mgoerens** [comment]
@acmenezes Do we even need to wait for the installPlan to be created ? The only reason we are waiting for it to be created is to approve it (if installPlanApproval is `Manual`)

If we force installPlanApproval to `Automatic` we might don't need the whole `approveInstallPlan` part.

See commit b91b372af0bf8e3a911e202e8b40daff84b602e0

**Comment by acmenezes** [comment]
> @acmenezes Do we even need to wait for the installPlan to be created ? The only reason we are waiting for it to be created is to approve it (if installPlanApproval is `Manual`)
> 
> If we force installPlanApproval to `Automatic` we might don't need the whole `approveInstallPlan` part.
> 
> See commit [b91b372](https://github.com/opdev/opcap/commit/b91b372af0bf8e3a911e202e8b40daff84b602e0)

Hi @mgoerens , I guess that may be right. We need to test this code without the installPlan part and see what happens. If we wait the CSVs that should be enough. I guess it takes a full run to make sure. Let me know when it's ready and I can test it as well.

**Comment by mgoerens** [comment]
It's ready. I tested, but not on a full run (ctrl+C after a few operators). I will re-run it locally.

I'd appreciate if you could also test it.

**Comment by mgoerens** [comment]
Okay, so I need to ask: how do you test ?

I ran into a couple of issues while testing on a full run:
- in the middle of the run, my CRC VM crashes, invalidating the tests (how to know if things are going wrong because of the changes VS because CRC is unstable ?) I decided to delete & recreate. I might need to provision a SNO if that continues to crash.
- some operators are failing but .. how to know if this is actually due to my changes ? I don't know the reason for the failure. I think we could look into improving error logging here.

So, how do you currently test opcap ?

**Comment by acmenezes** [comment]
> Okay, so I need to ask: how do you test ?
> 
> I ran into a couple of issues while testing on a full run:
> 
> * in the middle of the run, my CRC VM crashes, invalidating the tests (how to know if things are going wrong because of the changes VS because CRC is unstable ?) I decided to delete & recreate. I might need to provision a SNO if that continues to crash.
> * some operators are failing but .. how to know if this is actually due to my changes ? I don't know the reason for the failure. I think we could look into improving error logging here.
> 
> So, how do you currently test opcap ?

Hi @mgoerens , the best way to test it would be using a multi node cluster. CRC is good for development but certainly not for testing. Some operators will require more than one node to begin with.

**Comment by mgoerens** [comment]
@acmenezes Are all operators supposed to pass with a multi node cluster ? I guess not. How can I ensure the full run is providing expected results ?

**Comment by acmenezes** [comment]
> @acmenezes Are all operators supposed to pass with a multi node cluster ? I guess not. How can I ensure the full run is providing expected results ?

If you have all operators within the stdout.log file from a specific catalgo without breaking during the run it should be good. Of course if you run through 20 operators getting succeed or failed without any errors it's quite solid and shouldn't have any issues. I'm pulling the code here and testing as well.

**Comment by yashoza19** [comment]
Testing this PR now.

**Review by acmenezes — APPROVED** [review]
It looks good now! It's waiting for the CSV anyway so installPlan makes no sense anymore

**Review by yashoza19 — APPROVED** [review]
/approve

**Pull request merged**
