### PR TITLE
internal types package

### LINKED ISSUE #278: Refactoring: stack type goes better in a separate library
Since the stack type is generic and not necessarily related to capability we could use a different package to hold those types an allow it to be imported from multiple other points or even externally since it's pretty useful for many cases. Instead of having it on internal/capabilities/types.go we could provide a different package not sure what name and what this package could hold though.

### PR DESCRIPTION
**Pull request by skattoju**
## Description of PR
This PR moves the generic stack implemenetation currently in the capabilities package to a more generic place the current proposal being a types 
package under the internal package.

Fixes #278

## Changes (required)

- move generic stack implementation to internal/types package

## Checklist (required)
- [*] I have reviewed and followed the [contribution guidelines](https://github.com/opdev/opcap/blob/main/docs/contribution.md)
- [*] I have performed a self-review of my code
- [*] I have commented my code, particularly in hard-to-understand areas
- [*] I have made corresponding changes to the documentation if needed
- [*] I have checked that my changes pass all tests

### CODE REVIEW

**Review by bcrochet — COMMENTED** [review]
Two things.

1. Are you thinking that this will be uses somewhere other than the capability package? That's not clear here.
2. I'm not a fan of the 'types' package. If anything, I'd rather see this turn into a 'stack' package.

**Comment by skattoju** [comment]
> 1. Are you thinking that this will be uses somewhere other than the capability package? That's not clear here.
Not seeing it at the moment but potentially yes.

> 2. I'm not a fan of the 'types' package. If anything, I'd rather see this turn into a 'stack' package.
The types package would have both options and stack types for now.. could call it util or something more generic. options is needed by both reports and capability. 

Stack on the other hand although used only in capability is generic by design and even though it's not used anywhere today could be used in the future ? But not seeing it being used anywhere else at the moment as you pointed out..

**Comment by bcrochet** [comment]
> > 1. Are you thinking that this will be uses somewhere other than the capability package? That's not clear here.
> 
> Not seeing it at the moment but potentially yes.

Until we do, I think it's fine to stay where it is.

> 
> > 2. I'm not a fan of the 'types' package. If anything, I'd rather see this turn into a 'stack' package.
> 
> The types package would have both options and stack types for now.. could call it util or something more generic. options is needed by both reports and capability (#294 )
> 

Util is worse. :) And as I pointed out in #294, options should stay where it is.

> Stack on the other hand although used only in capability is generic by design and even though it's not used anywhere today could be used in the future ? But not seeing it being used anywhere else at the moment as you pointed out..

Let's not prematurely reorganize things if there is no immediate need to do so.

**Comment by acmenezes** [comment]
> Let's not prematurely reorganize things if there is no immediate need to do so.

@bcrochet @skattoju I would vote for a list package. That thing mimics a little bit a Python list somehow and could be improved to have other features. And I think that can actually be put on an actual pkg folder and not internal. It is useful anywhere already. This is the reason I opened the issue. Besides that moving that won't harm the project in any way.

**Comment by bcrochet** [comment]
> > Let's not prematurely reorganize things if there is no immediate need to do so.
> 
> @bcrochet @skattoju I would vote for a list package. That thing mimics a little bit a Python list somehow and could be improved to have other features. And I think that can actually be put on an actual pkg folder and not internal. It is useful anywhere already. This is the reason I opened the issue. Besides that, moving it won't harm the project in any way.

1. I'm not sure that 'list' would be the right place either. list.Stack just seems... wrong.
2. Not a fan of 'pkg'. It's an artificial organization that a good swath of the Go community do not agree with. 
3. Do we really want to start exposing things out of internal? That comes with having to maintain the API for external use. I'm not sure I want to go there.

**Comment by skattoju** [comment]
This would still be internal and wouldn't really change things up too much. Open to alternative suggestions to types.Stack could also close this one and leave things as is lmk what y'all think.

**Comment by skattoju** [comment]
Closing since there is no explicit need at this time.

**Pull request closed without merging**
