### PR TITLE
Adding a GH Action for testing a pull request

### PR DESCRIPTION
**Pull request by itroyano**
The following action will do the following on a PR to main:
1. run gofumpt on the code.
2. integrate with Coveralls for a coverage score.

Signed-off-by: Igor Troyanovsky <itroyano@redhat.com>

### CODE REVIEW

**Comment by itroyano** [comment]
Quick note - I used Coveralls since that works well in Preflight.
But I've seen repos that use CodeCov instead, which looks good too.   each has its pros and cons https://stackshare.io/stackups/codecov-vs-coveralls

cc: @bcrochet

**Review by yuriolisa — APPROVED** [review]

**Review by acmenezes — CHANGES_REQUESTED** [review]
Hi @itroyano , looks good. Can you please attach the issue number that this PR is closing?

**Comment by itroyano** [comment]
Fixes #186

**Review by acmenezes — APPROVED** [review]
Looks good.

**Review by yashoza19 — APPROVED** [review]
/approve

**Review by acmenezes — APPROVED** [review]
/lgtm

**Pull request merged**
