### PR TITLE
Fix CSVList for the right operator

### PR DESCRIPTION
**Pull request by yuriolisa**
Signed-off-by: Yuri Sa <yurimsa@gmail.com>

The function extractAlmExamples now iterate through CSVList.Items testing if we are getting values from the right CSV file, avoiding getting values from the first CSV returned from the List.

Refers #258 

## Changes (required)

- Added iteration through CSVList.Items.
- Added check if we are getting the right values.

## Checklist (required)
- [x] I have reviewed and followed the [contribution guidelines](https://github.com/opdev/opcap/blob/main/docs/contribution.md)
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation if needed
- [x] I have checked that my changes pass all tests

## References (optional)

### CODE REVIEW

**Review by bcrochet — APPROVED** [review]
/lgtm

**Review by bcrochet — CHANGES_REQUESTED** [review]
Need to fix the commits. This definitely doesn't need 5 commits, and it looks like there is an extra.

**Comment by yuriolisa** [comment]
@bcrochet, I've squashed four of them. Could you please review it again?

**Review by bcrochet — CHANGES_REQUESTED** [review]
There is still an extra commit here.

**Review by skattoju — APPROVED** [review]

**Review by yashoza19 — APPROVED** [review]
/approve

**Pull request merged**
