### PR TITLE
naming the workflow for prow compatibility

### LINKED ISSUE #219: GH Workflow naming must be compatible with Prow
In order to watch the workflow from Prow, it needs to have meaningful, short names with no caps and no spaces.

### PR DESCRIPTION
**Pull request by itroyano**
fixes #219

### CODE REVIEW

**Comment by mrhillsman** [comment]
@itroyano i was thinking more specific to the tests. iirc you have formatting and coverage tests right? so it would be nice to have the checks reflect that. the coverage/coveralls is a good example.

**Comment by itroyano** [comment]
Thanks @bcrochet for fixing the branch!

Hi @mrhillsman,
both are interconnected.
the code gets formatted and then test are run as make cover to get the result and convert it into Coveralls’ format.
If we want to split, there are 2 options -
  1.    do actions/checkout@v2 twice (both in syntax.yml and run-ci-tests.yml) and have both trigger on PR.
         that also means the run-ci will be looking at the unformatted code.
  2.  have run-ci-tests.yml be a reusable action similar to [Preflight's release-artifacts](https://github.com/itroyano/openshift-preflight/blob/main/.github/workflows/build-release.yml#L72)  .  I’m not sure it’s generic enough to be that.

**Comment by mrhillsman** [comment]
@itroyano rebase and we can figure it out later this is fine

**Comment by itroyano** [comment]
Closing this PR as discussed in Slack.
Can re-create it later if Prow needs it.

**Pull request closed without merging**
