### PR TITLE
Add newline after each json report object

### LINKED ISSUE #314: operatorJsonReportTemplate newline missing after each report
## Bug Description
When attempting to perform an upload of the report an error occurs related to each operator report in operator_install_report.json not being on a new line.

### PR DESCRIPTION
**Pull request by mrhillsman**
Fixes #314

Signed-off-by: Melvin Hillsman <mhillsma@redhat.com>

### CODE REVIEW

**Review by bcrochet — APPROVED** [review]
/lgtm

**Review by skattoju4 — APPROVED** [review]
/lgtm

**Review by skattoju — APPROVED** [review]
/lgtm

**Review by skattoju — APPROVED** [review]
/approve

**Pull request merged**
