### PR TITLE
add test for the check filtered results function

### PR DESCRIPTION
**Pull request by OchiengEd**
Add a unit test for the check filtered results function

Signed-off-by: Edmund Ochieng <ochienged@gmail.com>

### CODE REVIEW

**Review by acmenezes — CHANGES_REQUESTED** [review]
@OchiengEd, thanks for the PR! Do you have an issue for this one? If not could you please open one and link to this PR?

**Comment by OchiengEd** [comment]
@acmenezes  I have created issue #184 for this pull request.

Closes #184

**Comment by acmenezes** [comment]
> @acmenezes I have created issue #184 for this pull request.
> 
> Closes #184

Thanks @OchiengEd !

**Review by acmenezes — APPROVED** [review]
Looks good.

**Pull request merged**
