### PR TITLE
Create uploadPreRunE and uploadRunE

### LINKED ISSUE #197: Refactor upload.go
Move func expressions for PreRunE and RunE to named functions that will be called by PreRunE and RunE.

### PR DESCRIPTION
**Pull request by mrhillsman**
Signed-off-by: Melvin Hillsman <mhillsma@redhat.com>

## Description of PR
Refactor PreRunE and RunE function expressions into named functions in order to make testing easier.

Fixes #197

## Changes (required)
see description

## Checklist (required)
- [x] I have reviewed and followed the [contribution guidelines](https://github.com/opdev/opcap/blob/main/docs/contribution.md)
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation if needed
- [x] I have checked that my changes pass all tests

### CODE REVIEW

**Review by yashoza19 — COMMENTED** [review]
Hey @mrhillsman , What do you think about moving the upload functions within the internal package instead of adding all code in upload.go itself. Something like Brad suggested with this PR: https://github.com/opdev/opcap/pull/179/commits/fbc91275216a16662070efd09c566217dc813a04

**Comment by mrhillsman** [comment]
> Hey @mrhillsman , What do you think about moving the upload functions within the internal package instead of adding all code in upload.go itself. Something like Brad suggested with this PR: [fbc9127](https://github.com/opdev/opcap/commit/fbc91275216a16662070efd09c566217dc813a04)
> 
> We can have the tests in the same internal package.

As of today I don't think it matters one way or the other. The referenced PR does more than touch upload at the moment.

**Review by bcrochet — APPROVED** [review]
/lgtm

**Pull request merged**
