### PR TITLE
Update documentation with contribution guidelines

### LINKED ISSUE #161: Add contribution guidelines and building instructions to opcap README
On building include:

- [x] Requirements
- [x] Testing, compiling and versioning
- [x] Tips on troubleshooting and debugging with VSCode

On community contribution include:

- [x] Contribution policy
- [x] Weekly meeting and forum channels
- [x] Note on opening Issues and PRs - contribution guide

### PR DESCRIPTION
**Pull request by acmenezes**
This PR includes

 Requirements
 Testing, compiling and versioning
 Tips on troubleshooting and debugging with VSCode
 Contribution policy
 Weekly meeting and forum channels
 Note on opening PRs

closes #161

### CODE REVIEW

**Review by yashoza19 — APPROVED** [review]
/approve

**Comment by yashoza19** [comment]
Thanks @acmenezes  for submitting this. Since you covered the debugging part as well, should we close this PR: #137 ?

**Comment by acmenezes** [comment]
> Thanks @acmenezes for submitting this. Since you covered the debugging part as well, should we close this PR: #137 ?

@yashoza19 , I guess the answer is yes. We can always improve the new documentation though. So other PRs are welcome when this one lands.

**Pull request merged**
